### ISSUE TITLE
Implement netlify-cms frontend

### ISSUE THREAD

**Issue by 0xJem** [OlympusDAO/olympus-docs#12]
I suggest to have a specific branch (e.g. `content`, branched from master or staging) that has an active deployment of netlify-cms. Any changes made will go into this branch.

We will need to figure out who will be responsible for monitoring and merging changes.

**Comment by appleseed-iii** [comment]
CMS is config'd and run from the `netlify-cms` branch but reads/writes to main. This way if a pr is deployed/merged from the CMS it actually deploys to prod. The only time the `netlify-cms` needs to be updated is if you're updating the CMS config.

I noted this logic in the README in case we decide to tweak it in the future.
